Simulysis/Models/AnalysisView.cs
using Entities.Types;
using System.ComponentModel.DataAnnotations;
using Entities.DTO;


namespace Simulysis.Models
{
    public class AnalysisView
    {
        [Display(Name = "New Version")]
        [Required(ErrorMessage = "New version required.")]
        public int NewVersion { get; set; }

        [Display(Name = "Old Version")]
        [Required(ErrorMessage = "Old version required.")]
        public int OldVersion { get; set; }

        public IEnumerable<dynamic> Items { get; set; }
        public IEnumerable<ColumnProp> ColumnProps { get; set; }
        public int ItemPerPage { get; set; }
        public int CurrentPage { get; set; }
        public IEnumerable<int> PageSizes { get; set; }
        public string LinkAction { get; set; }
        public string LinkController { get; set; }
        public string PropUseToDelete { get; set; }
        public string SearchContent { get; set; }

        public int PageCount()
        {
            return Convert.ToInt32(Math.Ceiling(Items.Count() / (double)ItemPerPage));
        }

        public List<dynamic> PaginatedItems()
        {
            int start = (CurrentPage - 1) * ItemPerPage;
            return Items.Skip(start).Take(ItemPerPage).ToList();
        }

        public List<DeleteView> DeleteViews { get; set; }
    }
}

Simulysis/Controllers/APIs/FilesController.cs
using DAO.DAO.Factory;
using DAO.DAO.InterfaceDAO;
using Entities.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Simulysis.Controllers.APIs
{
    [AllowAnonymous]
    [ApiController]
    [Route("api/[controller]")]
    public class FilesController : ControllerBase
    {
        private static IProjectFileDAO projectFileDAO = DAOFactory.GetDAO("IProjectFileDAO") as IProjectFileDAO;

        [HttpGet]
        public IActionResult GetFileRelationships(long projId)
        {
            List<ProjectFileDTO> files = projectFileDAO.ReadAllFiles(projId, true);

            return Ok(files);
        }
    }
}

Simulysis/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Simulysis.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Simulysis/Controllers/AnalysisController.cs
using Common;
using DAO.DAO.Factory;
using DAO.DAO.InterfaceDAO;
using Entities;
using Entities.DTO;
using Entities.Logging;
using Entities.Types;
using Microsoft.AspNetCore.Mvc;
using Simulysis.Helpers;
using Simulysis.Helpers.DataSaver;
using Simulysis.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Octokit;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.Ajax.Utilities;
using System;

using System.Net.Http;
using System.Security.AccessControl;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using MySqlX.XDevAPI;
using System.Data.SqlClient;
using System.Data;
using System.Drawing;
using OfficeOpenXml;
using MySql.Data.MySqlClient;
using DAO.DAO.SqlServerDAO.FileContent;

using MySqlX.XDevAPI.Relational;
using Microsoft.Office.Interop.Excel;
using Constants = Common.Constants;
using DataTable = System.Data.DataTable;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace Simulysis.Controllers
{
    public class AnalysisController : Controller
    {
        IProjectDAO projectDAO = DAOFactory.GetDAO("IProjectDAO") as IProjectDAO;
        IProjectFileDAO projectFileDAO = DAOFactory.GetDAO("IProjectFileDAO") as IProjectFileDAO;
        IFilesRelationshipDAO fileRelationshipDAO = DAOFactory.GetDAO("IFilesRelationshipDAO") as IFilesRelationshipDAO;

        private readonly IWebHostEnvironment webHostEnvironment;

        private static string repositoryOwner;
        private static string repositoryName;
        private static IEnumerable<TreeItem> Files;

        // Notice: FK_ProjectFileId in deleteds are mapped to corresponding FK_ProjectFileId in added.
        private static List<LineDTO> deletedLineFilesDTO = new List<LineDTO>();
        private static List<LineDTO> addedLineFilesDTO = new List<LineDTO>();
        private static List<SystemDTO> deletedSystemFilesDTO = new List<SystemDTO>();
        private static List<SystemDTO> addedSystemFilesDTO = new List<SystemDTO>();
        private static List<SystemDTO> changedSystemFilesDTO = new List<SystemDTO>();
        private static List<long> treeImpactSet = new List<long>();
        private static List<ProjectFileDTO> impactSetProjectFileDTO = new List<ProjectFileDTO>();
        private static List<SystemDTO> impactSetSystemDTO = new List<SystemDTO>();

        // Version names:
        private static string newVersionName;
        private static string oldVersionName;

        // Current dig depth value:
        private static int curDigDepthValue;

        //Added Files list for tree highlight
        private static List<string> addedFilesDTO = new List<string>();
        public AnalysisController(IWebHostEnvironment webHostEnvironment)
        {
            this.webHostEnvironment = webHostEnvironment;
        }


        // GET: Project
        public ActionResult Index(TableView prevModel)
        {
            Loggers.SVP.Info("Get list of projects");

            var viewModel = new TableView()
            {
                ItemPerPage = Convert.ToInt32(Request.Query["show"].ToString() == "" ? 10 : Request.Query["show"].ToString()),
                PageSizes = new List<int>() { 10, 20, 50, 100 },
                CurrentPage = Convert.ToInt32(Request.Query["page"].ToString() == "" ? 1 : Request.Query["page"].ToString()),
                SearchContent = prevModel.SearchContent ?? "",
                ColumnProps = new List<ColumnProp>()
                {
                    new ColumnProp("Name", "Project name", 35),
                },
                LinkAction = "Index",
                LinkController = "Analysis",
                PropUseToDelete = "Id"
            };

            viewModel.DeleteViews = new List<DeleteView>();
            viewModel.Items = projectDAO.ReadAllProjects()
                .FindAll(project => project.Name.ToLower().Contains(viewModel.SearchContent.ToLower()));

            foreach (dynamic i in viewModel.PaginatedItems())
            {
                viewModel.DeleteViews.Add(new DeleteView()
                {
                    IdToDelete = i.GetType().GetProperty(viewModel.PropUseToDelete).GetValue(i),
                });
            }

            Loggers.SVP.Info($"List of {viewModel.ItemPerPage} at page {viewModel.CurrentPage}");


            return View(viewModel);

        }

        [Route("Analysis/Index/{projectId}")]
        public ActionResult Index(TableView prevModel, long projectId)
        {
            Loggers.SVP.Info("Get list of projects");

            var viewModel = new TableView()
            {
                ItemPerPage = Convert.ToInt32(Request.Query["show"].ToString() == "" ? 10 : Request.Query["show"].ToString()),
                PageSizes = new List<int>() { 10, 20, 50, 100 },
                CurrentPage = Convert.ToInt32(Request.Query["page"].ToString() == "" ? 1 : Request.Query["page"].ToString()),
                SearchContent = prevModel.SearchContent ?? "",
                ColumnProps = new List<ColumnProp>()
                {
                    new ColumnProp("Name", "Project name", 35),
                },
                LinkAction = "Index",
                LinkController = "Analysis",
                PropUseToDelete = "Id"
            };

            viewModel.DeleteViews = new List<DeleteView>();
            viewModel.Items = projectDAO.ReadAllProjects()
                .FindAll(project => project.Name.ToLower().Contains(viewModel.SearchContent.ToLower()));

            foreach (dynamic i in viewModel.PaginatedItems())
            {
                viewModel.DeleteViews.Add(new DeleteView()
                {
                    IdToDelete = i.GetType().GetProperty(viewModel.PropUseToDelete).GetValue(i),
                });
            }

            Loggers.SVP.Info($"List of {viewModel.ItemPerPage} at page {viewModel.CurrentPage}");
            Loggers.SVP.Info("show a project file");

            ProjectDTO project = projectDAO.ReadProjectById(projectId);
            ViewBag.ProjectName = project.Name;
            ViewBag.ProjectId = project.Id;

            ViewBag.FileName = project.Name;
            ViewBag.FileId = 0;
            ViewBag.SystemLevel = "Root";
            ViewBag.SwapView = Request.Query["swap"].ToString();
            ViewBag.FullNet = Request.Query["fullNet"].ToString();
            ViewBag.DisplayParents = Request.Query["displayParents"].ToString() ?? "true";
            ViewBag.DisplayEquals = Request.Query["displayEquals"].ToString() ?? "true";
            ViewBag.DisplayChildren = Request.Query["displayChildren"].ToString() ?? "false";
            ViewBag.DisplaySubChildren = Request.Query["displaySubChildren"].ToString() ?? "";
            ViewBag.DisplayChildLibraries = Request.Query["displayChildLibraries"].ToString() ?? "true";
            ViewBag.DisplayTreeView = "true";
            ViewBag.ViewType = string.IsNullOrEmpty(Request.Query["viewType"].ToString())
                ? Constants.INOUT_VIEW_TYPE
                : Request.Query["viewType"].ToString();
            ViewBag.WWWRoot = Configuration.WWWRoot;
            ViewBag.RootSysId = Request.Query["rootSysId"];

            return View(viewModel);
        }

        [Route("Analysis/Index/{projectId}/{fileId}")]
        public ActionResult Index(TableView prevModel, long projectId, long fileId)
        {
            Loggers.SVP.Info("Get list of projects");

            var viewModel = new TableView()
            {
                ItemPerPage = Convert.ToInt32(Request.Query["show"].ToString() == "" ? 10 : Request.Query["show"].ToString()),
                PageSizes = new List<int>() { 10, 20, 50, 100 },
                CurrentPage = Convert.ToInt32(Request.Query["page"].ToString() == "" ? 1 : Request.Query["page"].ToString()),
                SearchContent = prevModel.SearchContent ?? "",
                ColumnProps = new List<ColumnProp>()
                {
                    new ColumnProp("Name", "Project name", 35),
                },
                LinkAction = "Index",
                LinkController = "Analysis",
                PropUseToDelete = "Id"
            };

            viewModel.DeleteViews = new List<DeleteView>();
            viewModel.Items = projectDAO.ReadAllProjects()
                .FindAll(project => project.Name.ToLower().Contains(viewModel.SearchContent.ToLower()));

            foreach (dynamic i in viewModel.PaginatedItems())
            {
                viewModel.DeleteViews.Add(new DeleteView()
                {
                    IdToDelete = i.GetType().GetProperty(viewModel.PropUseToDelete).GetValue(i),
                });
            }

            Loggers.SVP.Info($"List of {viewModel.ItemPerPage} at page {viewModel.CurrentPage}");


            Loggers.SVP.Info("show a project file");

            ProjectDTO project = projectDAO.ReadProjectById(projectId);
            ViewBag.ProjectName = project.Name;
            ViewBag.ProjectId = project.Id;

            ProjectFileDTO projectFile = projectFileDAO.ReadFileById(fileId);
            ViewBag.FileName = projectFile.Name;
            ViewBag.FileId = projectFile.Id;
            ViewBag.SystemLevel = projectFile.SystemLevel;
            ViewBag.SwapView = Request.Query["swap"].ToString();
            ViewBag.FullNet = Request.Query["fullNet"].ToString();
            ViewBag.DisplayParents = Request.Query["displayParents"].ToString() ?? "true";
            ViewBag.DisplayEquals = Request.Query["displayEquals"].ToString() ?? "true";
            ViewBag.DisplayChildren = Request.Query["displayChildren"].ToString() ?? "false";
            ViewBag.DisplaySubChildren = Request.Query["displaySubChildren"].ToString() ?? "";
            ViewBag.DisplayChildLibraries = Request.Query["displayChildLibraries"].ToString() ?? "true";
            ViewBag.DisplayTreeView = "true";
            ViewBag.ViewType = string.IsNullOrEmpty(Request.Query["viewType"].ToString())
                ? Constants.INOUT_VIEW_TYPE

Simulysis/Views/Shared/_CompareTreePartial.cshtml
@model Simulysis.Models.TableView
@{
    ViewBag.UtilsForm = "projectSearch";
    ViewBag.Title = "Projects List";
    ViewBag.Controller = "Projects";
    ViewBag.ActiveTab = "All Projects";
    ViewBag.DeleteForm = "proj-del-form";
    ViewBag.ItemName = "projects";
    ViewBag.Title = ViewBag.FileName;
    ViewBag.CTitle = true;
    ViewBag.ActiveTab = ViewBag.ProjectName;
    ViewBag.Test = Model.Test;
}


<div class="col-2 position-relative" id="digDepthForm">
    <div class="row">
        <select class="" id="digDepth" name="digDepthValue" onchange="changeDigDepth()" >
            <option class="white" value="" selected disabled >Choose depth</option>
            <option value="1">Depth: 1</option>
            <option value="2">Depth: 2</option>
            <option value="3">Depth: 3</option>
            <option value="4">Depth: 4</option>
            <option value="5">Depth: 5</option>
        </select>
    </div>

</div>

<button id="impact-analyse-btn" class="btn btn-outline-info" style="display:inline; width: 130px;margin-left: 30px;" onclick="treeImpactAnalyse()">Show Impact</button>


<input type="hidden" id="newTreeImpactSet" value='@Json.Serialize(Model.treeImpactSet)' />

<script>
    document.getElementById('digDepth').value = @ViewBag.digDepthValue;
</script>



@*@using (Html.BeginForm("DigDepthChange", "Analysis", FormMethod.Post, new { enctype = "multipart/form-data", @class = "col-2 m-3", id = "digDepthForm" }))
    {
        <div class="row">
            <label asp-for="digDepth" class="sr-only"></label>
            <select class="form-control btn btn-outline-secondary" id="digDepth" name="digDepthValue" onchange="submitForm()">
                <option value="" disabled selected>@Html.DisplayNameFor(model => model.digDepth): @ViewBag.digDepthValue</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <input id="new-ver-id" type="hidden" name="newVersionId" value="@ViewBag.ProjectId" />
    }*@

Simulysis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Simulysis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Site/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Simulysis.styles.css" asp-append-version="true" />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Inter'>

</head>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<body>
    <div id="layout" style="display:flex; flex-direction:column;min-height:100%">
        <header>
            <div class="navBar">
                <div id="navbar-simulysis">
                    <div class="logoPart">
                        <a asp-controller="Home" asp-action="Index" class="">

                            <div class="logo">
                                <img src="~/images/_logo.svg" />
                            </div>
                            <div class="slogan">
                                <div class="">
                                    <h5>
                                        SIMULYSIS
                                    </h5>
                                </div>
                                <div class="">
                                    <p>
                                        SQA LAB
                                    </p>
                                </div>
                            </div>

                        </a>
                    </div>
                    

                    <div class="navMenu">
                        <ul class="navList">
                            <li class="navItem home onPage">
                                <a class="" asp-controller="Home" asp-action="Index">
                                    <p>HOME</p>
                                </a>
                            </li>
                            <li class="navItem project">
                                <a class="" asp-controller="Projects" asp-action="Index">
                                    <p>PROJECT</p>
                                </a>
                            </li>
                            <li class="navItem analysis">
                                <a class="" asp-controller="Analysis" asp-action="ProjectComparison">
                                    <p>
                                        ANALYSIS
                                    </p>
                                </a>
                            </li>
                            <li class="navItem about">
                                <a class="" asp-controller="About" asp-action="Index">
                                    <p>
                                        ABOUT
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <!---Main container class is for JS JQuery code to append elements-->
        <div class="main-container" style="box-shadow: 0 0.25rem 0.75rem 0.2rem rgba(0, 0, 0, .25) ;">
            <div class="main" >
                @RenderBody()
            </div>
        </div>

        <div class="d-flex text-muted" style="height: 120px; align-items:center; justify-content: center">
            <div class="container-fluid text-center" >
                &copy; 2023 - Simulysis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>

    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/floatthead/2.2.5/jquery.floatThead.min.js" integrity="sha512-131fDtJKn0jUOqN1sfcHkBZHRmTCP0gmcpztVNuE3M8toiuIv8V9I+tpL/1t3GFDBcigLyB2hWJ3ZNjYwEO4bg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Simulysis/Views/Shared/_Sidebar.cshtml
<div class="col-md-3 col-lg-2 border border-dark d-flex flex-column sidebar">
    <div class="nav-bar">

    </div>
    <div class="treeview">
        @*<div class="d-flex justify-content-end">
            <div id="sidebar-close" class="sidebar_controls-button">
                @Html.Partial("~/Views/Shared/Svg/_CloseIcon.cshtml")
            </div>
        </div>*@
        <ul class="treeview-section">
            <li class="treeview-expand">
                <div class="@(
                        ViewBag.ActiveTab == "All Projects" || ViewBag.ActiveTab == ViewBag.ProjectName
                        ? "treeview-caret treeview-caret--active" : "treeview-caret"
                    )">

                    @Html.Partial("~/Views/Shared/Svg/_CaretOutlined.cshtml")
                    Projects
                </div>
                <ul class="@(
                        (ViewBag.ActiveTab == "All Projects" || ViewBag.ActiveTab == ViewBag.ProjectName)
                        ? "treeview-nested treeview-nested--active" : "treeview-nested"
                    )">
                    <li class="@(ViewBag.ActiveTab == "All Projects" ? "treeview-active-tab" : "")">
                        @Html.ActionLink("All Projects", "Index", "Projects")
                    </li>
                    @if (ViewBag.ProjectName != null)
                    {
                        <li class="@(ViewBag.ActiveTab == ViewBag.ProjectName ? "treeview-active-tab" : "")">
                            @Html.ActionLink((string)ViewBag.ProjectName, "Index", "Files", new { projectId = ViewBag.ProjectId }, null)
                        </li>
                    }
                </ul>
            </li>
        </ul>

        <ul class="treeview-section">
            <li class="treeview-expand">
                <div class="@(
                        @*ViewBag.ActiveTab == "Users"*@
                            @*|| ViewBag.ActiveTab == "Role"*@
                        ViewBag.ActiveTab == "Logging"
                            || ViewBag.ActiveTab == "About"
                        ? "treeview-caret treeview-caret--active" : "treeview-caret"
                    )">

                    @Html.Partial("~/Views/Shared/Svg/_CaretOutlined.cshtml")
                    System
                </div>
                <ul class="@(
                        @*ViewBag.ActiveTab == "Users"
                            || ViewBag.ActiveTab == "Role"*@
                        ViewBag.ActiveTab == "Logging"
                            || ViewBag.ActiveTab == "About"
                        ? "treeview-nested treeview-nested--active" : "treeview-nested"
                    )">

                    @*<li class="@(ViewBag.ActiveTab == "Users" ? "treeview-active-tab" : "")">
                        @if(User.IsInRole("System Admin") || User.IsInRole("Project Admin"))
                        {
                            @Html.ActionLink("Users", "Index", "Users")
                        }
                        else
                        {
                            @Html.ActionLink("Users", "Properties", "Users")
                        }
                    </li>
                    <li>
                        Role
                    </li>*@
                    <li class="@(ViewBag.ActiveTab == "Logging" ? "treeview-active-tab" : "")">
                        @Html.ActionLink("Logging", "Index", "LogConfig")
                    </li>

                    <li class="@(ViewBag.ActiveTab == "About" ? "treeview-active-tab" : "")">
                        @Html.ActionLink("About", "Index", "About")
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

Simulysis/Views/Shared/_SignalTable.cshtml
<div class="signal-table">
    <table class="table table-bordered table-hover table-striped">
        <tbody id="bodyResult"></tbody>
    </table>
    <div id="signalPagination" class="mb-4">
        <form class="small-form">
            <div class="row small-form-row justify-content-end">
                <div class="small-form-col--sm small-form-group small-form-group--center justify-content-end">
                    <label class="control-label mb-0" for="tablePagiSize">Size:</label>
                </div>

                <div class="small-form-col--sm small-form-group small-form-group--right">
                    <select id="tablePagiSize" name="tablePagiSize" class="form-control">
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
</div>